### ISSUE TITLE
automatically generate readme for docker hub

### ISSUE THREAD

**Issue by McPringle** [McPringle/apus#289]
The README for the Docker Hub repository is limited to 2'000 characters. Actually there is a separate file: `README_DOCKERHUB.md`

A better solution (to avoid duplicate docs) would be to generate this file automatically by extracting the relevant paragraphs from the main `README.md` file. I found a GitHub action which looks like an easy solution:

https://github.com/sean0x42/markdown-extract

This should be added to the `Docker Nightly` action as the second last step just before the `Docker Hub Description` step.

**Comment by uzoltan** [comment]
I would like to give this a try tomorrow

**Comment by McPringle** [comment]
You are welcome! :-)

**Comment by McPringle** [comment]
Tipp: Create a new GitHub Action first, which only creates the new file. There is a tool called `act` which is able to test GitHub Actions locally:

https://github.com/nektos/act

A simple GitHub Action could be:

```yaml
name: Docker Hub Readme

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  readme:
    runs-on: ubuntu-latest
    name: Create Readme file for Docker Hub

    steps:
      - uses: actions/checkout@v4
      - name: Generate the file
...
      - name: Show generated file
        run: cat TESTFILE.md
```

Then you can run the local test with the name of the job:

`act -j readme`

That should help.

Btw: The first start of `act` takes a long time because it has to download a huge Docker image (49 GB) containing the GitHub Action stuff.

**Comment by uzoltan** [comment]
Cool, I will take a look at the testing. I have the first version of the github action step done, but I only tested the regex pattern itself via the markdown-extract docker image, not the GitHub action itself.

**Comment by uzoltan** [comment]
Which commit message emoji should I use for this issue by the way? :)

**Comment by McPringle** [comment]
Maybe one of these:

📝 Add or update documentation
👷 Add or update CI build system
🔧 Add or update configuration files

I think 🔧 might fit the best because at the end it is just a configuration of an existing GitHub Action file. But feel free to choose one you think it fits better: https://gitmoji.dev/

**Comment by uzoltan** [comment]
This tip was very useful actually, the regex pattern argument breaks somehow through the github action, I am expecting it has to do somehow with the fact that one of the headers I want to extract contains whitespace (Copyright and License), because the others do not contain whitespace, and it fails on this one

I will post my `act` test results here, once it is working

**Comment by uzoltan** [comment]
I am a bit stuck, hoping it is not a problem with me using WSL on my home PC:

```
[Docker Hub Readme/Create Readme file for Docker Hub] ⭐ Run Main print current dir
[Docker Hub Readme/Create Readme file for Docker Hub]   🐳  docker exec cmd=[bash -e /var/run/act/workflow/0] user= workdir=
| total 8
| drwxr-xr-x 2 root root 4096 Mar  1 10:13 .
| drwxr-xr-x 3 root root 4096 Mar  1 10:13 ..
| /mnt/c/Users/Zoli/IdeaProjects/apus
[Docker Hub Readme/Create Readme file for Docker Hub]   ✅  Success - Main print current dir
[Docker Hub Readme/Create Readme file for Docker Hub] ⭐ Run Main Extract Docker Hub README
[Docker Hub Readme/Create Readme file for Docker Hub]   🐳  docker build -t act-sean0x42-markdown-extract-v2-dockeraction:latest C:\Users\Zoli\.cache\act\sean0x42-markdown-extract@v2\.github\action\
[Docker Hub Readme/Create Readme file for Docker Hub]   🐳  docker pull image=act-sean0x42-markdown-extract-v2-dockeraction:latest platform= username= forcePull=false
[Docker Hub Readme/Create Readme file for Docker Hub]   🐳  docker create image=act-sean0x42-markdown-extract-v2-dockeraction:latest platform= entrypoint=[] cmd=["^(Apus|Features|Configuration|Production|Communication)" "README.md"] network="container:act-Docker-Hub-Readme-Create-Readme-file-for-Docker-Hub-840cf9baa332c8e5202d4f6313a478d86fb5a055b91098f97c8f05f51e796ccf"
[Docker Hub Readme/Create Readme file for Docker Hub]   🐳  docker run image=act-sean0x42-markdown-extract-v2-dockeraction:latest platform= entrypoint=[] cmd=["^(Apus|Features|Configuration|Production|Communication)" "README.md"] network="container:act-Docker-Hub-Readme-Create-Readme-file-for-Docker-Hub-840cf9baa332c8e5202d4f6313a478d86fb5a055b91098f97c8f05f51e796ccf"
| Error: Unable to extract at path: README.md
|
| Caused by:
|     No such file or directory (os error 2)
```

It seems the containers ran by `act` do not see the contents of `/mnt/c/Users/Zoli/IdeaProjects/apus`. Maybe I need a volume mount.


Alternatively, when I first lunched act, I chose the medium size download option, maybe I need to bite the bullet and download the large one with the ~75 gigs of storage requirement.

**Comment by McPringle** [comment]
You can try to list all files available to the build by adding a `run` configuration:

```yaml
      - name: Show files
        run: ls -lah
```

The output should look like this:

```
| total 1.8M
| drwxr-xr-x 7 runner docker 4.0K Mar  1 10:31 .
| drwxr-xr-t 3 root   root   4.0K Mar  1 10:31 ..
| -rw-rw-r-- 1 runner docker 4.9K Feb 27 21:46 .all-contributorsrc
| -rw-rw-r-- 1 runner docker  28K Nov  8 09:48 .editorconfig
| drwxr-xr-x 7 runner docker 4.0K Mar  1 10:31 .git
| -rw-rw-r-- 1 runner docker   52 Nov  8 09:48 .gitattributes
| drwxr-xr-x 4 runner docker 4.0K Mar  1 10:31 .github
| -rw-rw-r-- 1 runner docker  989 Feb  7 13:09 .gitignore
| -rw-rw-r-- 1 runner docker  754 Nov  8 09:48 .gitpod.Dockerfile
| -rw-rw-r-- 1 runner docker  345 Nov  8 09:48 .gitpod.yml
| drwxr-xr-x 3 runner docker 4.0K Mar  1 10:31 .mvn
| -rw-rw-r-- 1 runner docker  112 Feb  7 13:09 .sdkmanrc
| -rw-rw-r-- 1 runner docker 3.5K Feb 22 15:49 CHANGELOG.md
| -rw-rw-r-- 1 runner docker 1.4K Feb 19 08:23 DCO.md
| -rw-rw-r-- 1 runner docker  339 Feb 21 14:08 Dockerfile
| -rw-rw-r-- 1 runner docker  34K Nov  8 09:48 LICENSE.md
| -rw-rw-r-- 1 runner docker  33K Feb 27 21:50 README.md
| -rw-rw-r-- 1 runner docker  17K Feb 28 08:15 README_DOCKERHUB.md
| -rw-rw-r-- 1 runner docker 7.9K Nov  8 09:48 checkstyle.xml
| drwxr-xr-x 4 runner docker 4.0K Mar  1 10:31 frontend
| -rwxrwxr-x 1 runner docker  11K Feb  7 13:09 mvnw
| -rw-rw-r-- 1 runner docker 6.9K Feb  7 13:09 mvnw.cmd
| -rw-rw-r-- 1 runner docker 618K Feb 12 16:43 package-lock.json
| -rw-rw-r-- 1 runner docker 3.7K Feb 12 16:42 package.json
| -rw-rw-r-- 1 runner docker  25K Feb 27 12:55 pom.xml
| -rw-rw-r-- 1 runner docker  762 Feb  7 13:09 renovate.json
| -rw-rw-r-- 1 runner docker  575 Nov  8 09:48 ruleset.xml
| -rw-rw-r-- 1 runner docker 197K Nov  8 09:48 screenshot-baselone.webp
| -rw-rw-r-- 1 runner docker 194K Nov  8 09:48 screenshot-default.webp
| -rw-rw-r-- 1 runner docker 234K Nov  8 09:48 screenshot-javaland.webp
| -rw-rw-r-- 1 runner docker 274K Nov  8 09:48 screenshot-jfs.webp
| drwxr-xr-x 4 runner docker 4.0K Mar  1 10:31 src
| -rw-rw-r-- 1 runner docker  275 Nov  8 09:48 vite.config.ts
```

For me, the medium one works - but I'm not on Windows.

Edit: You should add it right after the checkout step.

**Comment by uzoltan** [comment]
Yep, `ls` is responsible for these 2 lines on my machine. 
```
| drwxr-xr-x 2 root root 4096 Mar  1 10:13 .
| drwxr-xr-x 3 root root 4096 Mar  1 10:13 ..
```

```
    steps:
      - name: print current dir
        run: |
          ls -lah
          pwd
```

I am trying to figure out how to convince `act` to give me the option to choose the large option :D reinstalling the cli and deleting its docker images was not enough.

**Comment by McPringle** [comment]
There is an `actrc` file somewhere. On Linux, it is in `~/.config/act/actrc`. Just delete it and on the next run it will ask again which image to use.

Edit: But I think the problem must be somewhere else.

**Comment by McPringle** [comment]
Maybe this link here helps: https://medium.com/@debasishkumardas5/running-github-actions-locally-a-complete-guide-for-windows-mac-and-linux-users-34c45999c7cd

**Comment by uzoltan** [comment]
Adding the -b flag solved it!

`act -b -W '.github/workflows/readme.yml'`

I have a nice `cat` output now, without the `Copyright and License` header, I will revisit that issue after lunch.

**Comment by uzoltan** [comment]
My last hurdle seems to be the fact, that when I try to write the markdown output to file as the documentation suggest, or with echo:

```
- name: Write output to file
  run: |
    printf '${{ steps.extract-changelog.outputs.markdown }}' > CHANGELOG-extracted.txt
```

The shell commands, for example this one:
```shell
docker build -t apus .
```

are actually executed during this job step. The docker build fails, and I have a bunch of "command not found" logs, which is not ideal. But the file seems to be created well:

```
| -rwxrwxrwx 1 root root  33841 Mar  1 09:25 README.md
| -rw-r--r-- 1 root root  15822 Mar  1 12:52 README_DOCKERHUB.md
```

**Comment by uzoltan** [comment]
I was able to make it work with this example, in one of the issues of markdown-extractor: https://github.com/jayqi/gha-python-package-release-demo/blob/69c2db55b56a2a4eee1bf82467b87f47897c7bc9/.github/workflows/release.yml#L53-L57

I will cleanup my change and commits and open a PR soonish.

ack testing with this workflow:

```
name: Docker Hub Readme

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  readme:
    runs-on: ubuntu-latest
    name: Create Readme file for Docker Hub
    env:
      DOCKERHUB_README: "README_DOCKERHUB.md"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: extract-docker-hub-readme
        name: Extract Docker Hub README
        uses: sean0x42/markdown-extract@v2
        with:
          file: README.md
          pattern: 'Apus|Features|Configuration|Production|Communication|Copyright'
          include-all: true

      - name: Docker Hub README to file2TEST
        run: |
          cat <<'EOF' > $DOCKERHUB_README
          ${{ steps.extract-docker-hub-readme.outputs.markdown }}
          EOF

      - name: print current dir2
        run: |
          ls -la
          pwd
```

<img width="1675" alt="Image" src="https://github.com/user-attachments/assets/e8a64144-7f9a-4521-b9a1-e45a48515f7b" />

<img width="1240" alt="Image" src="https://github.com/user-attachments/assets/951e0a15-2ae9-403b-8935-fbe0ae85a6fa" />
